#include "App.hpp"
#include "core/Pending.hpp"
#include "core/Shortcuts.hpp"

#include <glibmm/miscutils.h>

#include <chrono>
#include <cstdlib>
#include <unistd.h>
#include <vector>
#include "Shell.hpp"
#include "Appearance.hpp"
#include "Log.hpp"

#include <gtkmm/icontheme.h>
#include <gdkmm/display.h>

// The RESOURCE-PIPELINE paradigm's build-side seam. The app logo ships in a
// compiled-in GResource bundle (resources/jot.gresource.xml -> jot-resources.c,
// generated by glib-compile-resources). Declared extern "C" because that
// generated source compiles as C -- so its getter has C linkage and there's no
// generated header to include or keep in sync. (docs/resources-and-dialog-lifetime.md)
extern "C" GResource* jot_resources_get_resource(void);

namespace jot {

Glib::RefPtr<App> App::create() {
    log::init();   // area loggers up before anything logs
    // ...and then, immediately, whatever the environment asked to hear. Before
    // the App exists, so nothing that logs during construction is missed.
    log::apply_debug_env(std::getenv("JOT_DEBUG"));
    return Glib::make_refptr_for_instance(new App());
}

App::App()
    : Gtk::Application("io.github.scott8420.Jot",
                       Gio::Application::Flags::HANDLES_COMMAND_LINE) {
    // Registered so `--help` lists it -- and registering it is ALSO what makes
    // GLib parse it, which is the part that bit. A registered option is REMOVED
    // from the argv that reaches on_command_line, so reading the flag out of
    // argv found nothing and every `jot --capture` silently became a plain
    // activation. The flag is read from the options dict; what is LEFT in argv
    // is the text.
    //
    // BOOL rather than STRING because `--capture` takes an OPTIONAL argument:
    // `jot --capture` (open the box) and `jot --capture "ring the vet"` (file it
    // silently) are both real uses, and a GOption entry can have one arity or
    // the other but not both.
    add_main_option_entry(Gtk::Application::OptionType::BOOL, "capture", 'c',
                          "Capture a thought. With words after it, file them without "
                          "opening jot; with nothing, open the capture line.");
}

// The parse, kept away from the plumbing. `capture_flag` comes from the options
// dict because GLib has already taken the flag out of argv. Several words are
// joined, so an unquoted `jot --capture ring the vet` does what it looks like it
// does rather than filing the word "ring".
App::Request App::parse(const std::vector<std::string>& argv, bool capture_flag) {
    Request r;
    r.capture = capture_flag;
    for (std::size_t i = 1; i < argv.size(); ++i) {
        if (argv[i].empty() || argv[i][0] == '-') continue;   // an option we do not own
        if (!r.text.empty()) r.text += " ";
        r.text += argv[i];
    }
    return r;
}

// ─────────────────────────────────────────────────────────────────────────────
// on_command_line -- the one place a second invocation lands.
//
// activate() first, always: whether this process is the one that will own the
// window or is only forwarding to it, there has to BE a window before anything
// can be captured into it. When jot is already running, activate() is a no-op
// that reaches the existing Shell.
//
// With text, the window is deliberately NOT presented. `jot --capture "milk"`
// from a script or a keybinding should not throw a window in front of whatever
// you are doing -- the note is filed and the terminal returns. Without text
// there is nothing to file, so the only sensible reading is "let me type", and
// that DOES present.
// ─────────────────────────────────────────────────────────────────────────────
int App::on_command_line(const Glib::RefPtr<Gio::ApplicationCommandLine>& cmd) {
    // giomm hands back a raw argv it OWNS the outer array of: the strings are
    // borrowed, the vector is ours to free. Copied into std::string straight
    // away so nothing downstream has to know that.
    int argc = 0;
    char** raw = cmd->get_arguments(argc);
    std::vector<std::string> argv;
    argv.reserve(static_cast<std::size_t>(argc));
    for (int i = 0; i < argc; ++i)
        if (raw && raw[i]) argv.emplace_back(raw[i]);
    g_strfreev(raw);

    // giomm does not wrap the options dict -- its own header says so -- so this
    // one lookup goes through the C API rather than inventing a second way to
    // get the flag across.
    bool capture_flag = false;
    if (GVariantDict* opts = g_application_command_line_get_options_dict(cmd->gobj())) {
        gboolean on = FALSE;
        if (g_variant_dict_lookup(opts, "capture", "b", &on)) capture_flag = on;
    }

    const Request r = parse(argv, capture_flag);
    // A capture with words in it is the one request that does NOT want to be
    // looked at: it comes from a script or a keybinding, and a window thrown in
    // front of whatever you were doing is the reason you would stop using it.
    const bool silent = r.capture && !r.text.empty();

    if (auto lg = log::get(log::Area::App))
        lg->debug("command-line: argc={} remote={} capture={} text='{}'", argc,
                  cmd->is_remote(), r.capture, r.text);

    // ── COLD CAPTURE: file it and go, with no window at all ────────────────
    // `is_remote()` false means this process IS the primary instance -- there
    // was no running jot to forward to. Starting the whole app to write one
    // line down is the behaviour this milestone exists to remove: the spool
    // takes it and the next launch drains it.
    if (silent && !cmd->is_remote()) {
        if (file_pending(r.text)) {
            // The terminal is the only surface this path has, so it says so.
            cmd->print("Filed. jot will pick it up next time it opens.\n");
            if (auto lg = log::get(log::Area::App))
                lg->info("cold capture -- spooled, no window");
            return 0;   // no window, no hold: the main loop has nothing left to do
        }
        // The spool is the only copy of what was typed, so a spool that failed
        // does not end in a shrug. Fall through and open jot, which turns an
        // unfilable capture into a live one rather than a lost one.
        cmd->printerr("jot: could not write to the pending folder; opening jot instead.\n");
        if (auto lg = log::get(log::Area::App))
            lg->error("cold capture -- spool write failed, falling back to opening jot");
    }

    // activate-or-repair, and present ONLY if something asked to be seen.
    ensure_shell(!silent);
    if (!m_shell) return 0;          // activation refused; nothing to capture into

    if (!r.capture) return 0;
    if (r.text.empty()) {
        m_shell->focus_capture_bar();
    } else {
        m_shell->capture(r.text);
        if (auto lg = log::get(log::Area::App)) lg->info("captured from the command line");
    }
    return 0;
}

// The XDG resolution is the UI layer's (core takes a plain path); the subpath
// is core's, so this and Shell::drain_pending cannot drift apart.
std::string App::pending_dir() const {
    return core::pending_dir(Glib::get_user_data_dir());
}

bool App::file_pending(const std::string& text) const {
    // The uniquifier only has to separate two captures taken in the same second.
    // A pid does that for separate invocations, which is what a cold capture
    // always is -- this process is about to exit.
    const auto now = std::chrono::duration_cast<std::chrono::seconds>(
                         std::chrono::system_clock::now().time_since_epoch())
                         .count();
    std::string wrote;
    if (!core::write_pending(pending_dir(), text, static_cast<std::int64_t>(now),
                             std::to_string(getpid()), &wrote))
        return false;
    if (auto lg = log::get(log::Area::Io)) lg->info("spooled a capture into {}", wrote);
    return true;
}

// The SHORTCUT-REGISTRY paradigm's other consumer. Accelerators are an
// application-scope concern (they survive window construction order), so they
// bind here -- and they are driven from the pure core::shortcut_registry(), the
// same list ShortcutsDialog documents from. Register a shortcut once THERE and
// both the key and its advertised row follow; there is no second list to update
// and therefore nothing to drift. Doc-only rows (gestures) carry no action and
// are skipped -- they document without binding.
void App::on_startup() {
    Gtk::Application::on_startup();

    // Registered in startup so it exists before any activation can dispatch to
    // it -- including the one GNOME performs when a tray notification is
    // clicked on a jot that is not running.
    add_action_with_parameter(
        "goto-node", Glib::VARIANT_TYPE_STRING,
        sigc::mem_fun(*this, &App::on_goto_node));

    // ── `app.quit`, and it is NOT decoration ───────────────────────────────
    // This is the action GNOME's Background Apps list activates over D-Bus when
    // you press Quit next to jot. GApplication exports org.freedesktop.
    // Application for free, and ActivateAction dispatches straight into this
    // group -- so an application that does not register a "quit" action is one
    // the Shell CANNOT ASK to stop, and it SIGKILLs the process instead. (KDE
    // hit this on the code they copied from gnome-shell's backgroundApps.js:
    // an app with no quit action gets killed, not asked.)
    //
    // For jot that would mean an unsaved scratch buffer dying with no prompt
    // and no chance to flush, in the one situation the milestone exists to
    // handle. So residency and this action arrive together, or residency is a
    // data-loss feature.
    //
    // Same reasoning as goto-node for it being on the APPLICATION: the request
    // arrives at a process whose window may have been closed an hour ago. It
    // does NOT activate() first, though -- unlike a notification click, "quit"
    // is not a reason to build a window. A quit with no Shell has nothing to
    // ask and nothing to save.
    add_action("quit", sigc::mem_fun(*this, &App::on_quit));
    for (const auto& s : core::shortcut_registry()) {
        if (s.action.empty() || s.accels.empty()) continue;
        std::vector<Glib::ustring> accels(s.accels.begin(), s.accels.end());
        set_accels_for_action(s.action, accels);
    }
}

// activate() FIRST, for the same reason on_command_line does it: the click may
// be arriving at a process that has no window yet, and there has to be a Shell
// before there is anything to reveal the node in. present() after, because
// unlike a scripted capture a notification click IS a request to be looked at.
void App::on_goto_node(const Glib::VariantBase& target) {
    auto v = Glib::VariantBase::cast_dynamic<Glib::Variant<Glib::ustring>>(target);
    const std::string id = v.get();
    if (id.empty()) return;

    activate();
    if (!m_shell) return;
    m_shell->present();
    m_shell->goto_note(id);
    if (auto lg = log::get(log::Area::App)) lg->info("notification opened node {}", id);
}

// The Shell owns the decision, because it is the only object that knows whether
// there are unsaved notes -- and it may present the window to ask. With no
// Shell there is nothing to ask about and nothing to lose, so the process goes.
void App::on_quit() {
    if (auto lg = log::get(log::Area::App)) lg->info("quit requested");
    if (m_shell) m_shell->request_quit();
    else quit();
}

// activate() means "show me jot", and that is what the launcher, the desktop
// file and a notification click all mean by it. Everything it actually DOES is
// one layer down, where presenting is a parameter rather than an assumption.
void App::on_activate() { ensure_shell(/*present=*/true); }

// ─────────────────────────────────────────────────────────────────────────────
// ensure_shell -- there is a Shell, it is attached, and it may or may not be on
// screen.
//
// The `present` parameter is s013's two-line fix for a bug s012 created: a
// resident jot has no window, so EVERY arrival -- including `jot --capture
// "milk"` from a keybinding -- pulled the app onto the screen. What must always
// happen (construct, attach, build) and what must happen only on request
// (present) were the same statement, and separating them is the whole change.
// ─────────────────────────────────────────────────────────────────────────────
void App::ensure_shell(bool present) {
    // ── IDEMPOTENT, and it was not until s008 ───────────────────────────────
    // Until `jot --capture` existed, activate() happened exactly once per
    // process and this override could afford to assume it. It cannot now: a
    // forwarded command line calls activate() on the ALREADY RUNNING instance,
    // and without this guard that built a SECOND Shell -- a second window, a
    // second core::Project over the same jots folder, two writers to one
    // jot.json, and every widget name duplicated in the registry.
    //
    // The registry warned about the duplicates, which is the registry doing
    // exactly the job it exists to do: the second Shell was announced in the
    // log before anything was lost.
    if (m_shell) {
        // ── RE-ATTACH, because a hidden window loses its application ───────
        // s012 found this the hard way: while resident,
        // Gtk::Window::get_application() on the hidden Shell returns NULL. A
        // window with no application cannot resolve `app.*` through the action
        // muxer, which is why a re-presented jot came back with its menu items
        // and widgets insensitive -- they were not disabled, they had nothing
        // to dispatch to.
        //
        // add_window() is idempotent, so this costs nothing on the path where
        // the link survived and repairs the one where it did not.
        if (!m_shell->get_application()) {
            add_window(*m_shell);
            if (auto lg = log::get(log::Area::App))
                lg->warn("re-attached the hidden Shell to the application");
        }
        // The re-attach above happens EITHER WAY. A silent capture still has to
        // land in a Shell whose `app.*` actions resolve -- it just does not get
        // to put a window in front of anybody.
        if (present) m_shell->present();
        else if (auto lg = log::get(log::Area::App))
            // The line to grep for when checking that a scripted capture did
            // not steal the screen. The trace channel for a claim whose other
            // channel is permanently Scott's eyes.
            lg->info("silent arrival -- the window was left exactly as it was");
        return;
    }

    // ── THE DESKTOP'S LIGHT/DARK PREFERENCE, FIRST, BEFORE ANY WINDOW ───────
    // GTK4 does not follow it on its own and jot does not link libadwaita,
    // so the app has to ask (see Appearance.hpp). Ahead of `new Shell()` on
    // purpose: the difference between starting dark and starting light and
    // repainting.
    //
    // It also has to be ahead of the icon theme work below. The logo is a
    // SYMBOLIC icon, which GTK recolours to the theme foreground -- so it
    // inherits the answer to this question rather than carrying an opinion of
    // its own, and that is exactly why the bundle ships one symbolic SVG
    // instead of a light and a dark PNG.
    appearance::follow_system();

    // Register the compiled-in bundle and point the icon theme at its icon
    // prefix, so set_icon_name("jot-logo-symbolic") resolves out of the binary
    // and GTK recolours it to the theme foreground -- no icon on the user's disk.
    // NB: add_resource_path gets .../icons; GTK appends scalable/apps/ itself.
    g_resources_register(jot_resources_get_resource());
    if (auto display = Gdk::Display::get_default()) {
        auto icons = Gtk::IconTheme::get_for_display(display);
        icons->add_resource_path("/io/github/scott8420/Jot/icons");
    }

    m_shell = new Shell();       // lifetime owned by the application
    add_window(*m_shell);
    m_shell->build_ui();
    // Unreachable today with present=false -- a cold capture spools instead of
    // building anything, and every other silent arrival finds a Shell already
    // up. Written honestly anyway: a window constructed and deliberately not
    // shown is the resident state jot already supports, not a special case.
    if (present) m_shell->present();
    if (auto lg = log::get(log::Area::App)) lg->info("jot activated");
}

}  // namespace jot
