#include "App.hpp"
#include "core/Pending.hpp"
#include "core/Tags.hpp"
#include "core/Shortcuts.hpp"

#include <glibmm/miscutils.h>
#include <glibmm/main.h>

#include <chrono>
#include <cstdlib>
#include <unistd.h>
#include <sys/stat.h>
#include <vector>
#include "Shell.hpp"
#include "Appearance.hpp"
#include "Log.hpp"

#include <gtkmm/icontheme.h>
#include <gdkmm/display.h>

// The RESOURCE-PIPELINE paradigm's build-side seam. The app logo ships in a
// compiled-in GResource bundle (resources/jot.gresource.xml -> jot-resources.c,
// generated by glib-compile-resources). Declared extern "C" because that
// generated source compiles as C -- so its getter has C linkage and there's no
// generated header to include or keep in sync. (docs/resources-and-dialog-lifetime.md)
extern "C" GResource* jot_resources_get_resource(void);

namespace jot {

Glib::RefPtr<App> App::create() {
    log::init();   // area loggers up before anything logs
    // ...and then, immediately, whatever the environment asked to hear. Before
    // the App exists, so nothing that logs during construction is missed.
    log::apply_debug_env(std::getenv("JOT_DEBUG"));
    return Glib::make_refptr_for_instance(new App());
}

App::App()
    : Gtk::Application("io.github.scott8420.Jot",
                       Gio::Application::Flags::HANDLES_COMMAND_LINE) {
    // s062e: remember which program file this is, to notice a rebuild later.
    {
        char buf[4096];
        const ssize_t n = readlink("/proc/self/exe", buf, sizeof buf - 1);
        if (n > 0) {
            m_exe.assign(buf, static_cast<std::size_t>(n));
            struct stat st{};
            if (::stat(m_exe.c_str(), &st) == 0) {
                m_exe_ino = static_cast<unsigned long long>(st.st_ino);
                m_exe_mtime = static_cast<long long>(st.st_mtime);
            }
        }
    }
    // Registered so `--help` lists it -- and registering it is ALSO what makes
    // GLib parse it, which is the part that bit. A registered option is REMOVED
    // from the argv that reaches on_command_line, so reading the flag out of
    // argv found nothing and every `jot --capture` silently became a plain
    // activation. The flag is read from the options dict; what is LEFT in argv
    // is the text.
    //
    // BOOL rather than STRING because `--capture` takes an OPTIONAL argument:
    // `jot --capture` (open the box) and `jot --capture "ring the vet"` (file it
    // silently) are both real uses, and a GOption entry can have one arity or
    // the other but not both.
    add_main_option_entry(Gtk::Application::OptionType::BOOL, "capture", 'c',
                          "Capture a thought. With words after it, file them without "
                          "opening jot; with nothing, open the capture line. #words become tags.");
    // s025c. BOOL for the same reason as --capture: GLib takes the flag, and
    // the NAME and items are what is left in argv.
    add_main_option_entry(Gtk::Application::OptionType::BOOL, "list", 'l',
                          "Add tasks to a list: jot --list NAME item [item...]. Grows the "
                          "note called NAME, or makes it. Quote an item of several words; "
                          "an item that is only #tags tags the note.");
    // s025d (Scott): the name is the first plain word; the flag says what to
    // add. `jot Groceries -a check the pantry first`.
    add_main_option_entry(Gtk::Application::OptionType::BOOL, "append", 'a',
                          "Add a line of text to a note: jot NAME -a words... Grows the note "
                          "called NAME, or makes it. Both at once: jot NAME -al \"a line\" "
                          "item [item...], or jot NAME -a words -l items.");
    // s071: answered in main.cpp before GTK starts (core::glance_command);
    // registered here only so `jot --help` lists it.
    add_main_option_entry(Gtk::Application::OptionType::BOOL, "glance", '\0',
                          "Print the Glance at Today -- late, due, flagged, errands -- and "
                          "exit; jot --glance ics prints it as a calendar file. Works with "
                          "jot closed, from cron too.");
    // s074: what the login autostart entry runs (install.sh). Starts jot
    // resident with no window -- the due clock and the capture door open from
    // login, nothing on the screen.
    add_main_option_entry(Gtk::Application::OptionType::BOOL, "background", '\0',
                          "Start jot with no window, running in the background (what "
                          "\"Start at login\" runs). With jot already running, does nothing.");
    // s061e: written by core::cli_join_append_list (main.cpp), not typed --
    // hidden from --help, which shows -al instead.
    add_main_option_entry(Gtk::Application::OptionType::BOOL, "both", '\0',
                          "A line and todos at once: --both NAME \"line\" item...", "",
                          Glib::OptionEntry::Flags::HIDDEN);
}

// The parse, kept away from the plumbing. `capture_flag` comes from the options
// dict because GLib has already taken the flag out of argv. Several words are
// joined, so an unquoted `jot --capture ring the vet` does what it looks like it
// does rather than filing the word "ring".
App::Request App::parse(const std::vector<std::string>& argv, bool capture_flag,
                        bool list_flag, bool append_flag, bool both_flag) {
    Request r;
    r.both = both_flag;
    r.capture = capture_flag;
    r.list = list_flag;
    r.append = append_flag;
    for (std::size_t i = 1; i < argv.size(); ++i) {
        if (argv[i].empty() || argv[i][0] == '-') continue;   // an option we do not own
        if (!r.text.empty()) r.text += " ";
        r.text += argv[i];
        r.words.push_back(argv[i]);
    }
    return r;
}

// ─────────────────────────────────────────────────────────────────────────────
// on_command_line -- the one place a second invocation lands.
//
// activate() first, always: whether this process is the one that will own the
// window or is only forwarding to it, there has to BE a window before anything
// can be captured into it. When jot is already running, activate() is a no-op
// that reaches the existing Shell.
//
// With text, the window is deliberately NOT presented. `jot --capture "milk"`
// from a script or a keybinding should not throw a window in front of whatever
// you are doing -- the note is filed and the terminal returns. Without text
// there is nothing to file, so the only sensible reading is "let me type", and
// that DOES present.
// ─────────────────────────────────────────────────────────────────────────────
int App::on_command_line(const Glib::RefPtr<Gio::ApplicationCommandLine>& cmd) {
    // giomm hands back a raw argv it OWNS the outer array of: the strings are
    // borrowed, the vector is ours to free. Copied into std::string straight
    // away so nothing downstream has to know that.
    int argc = 0;
    char** raw = cmd->get_arguments(argc);
    std::vector<std::string> argv;
    argv.reserve(static_cast<std::size_t>(argc));
    for (int i = 0; i < argc; ++i)
        if (raw && raw[i]) argv.emplace_back(raw[i]);
    g_strfreev(raw);

    // giomm does not wrap the options dict -- its own header says so -- so this
    // one lookup goes through the C API rather than inventing a second way to
    // get the flag across.
    bool capture_flag = false;
    if (GVariantDict* opts = g_application_command_line_get_options_dict(cmd->gobj())) {
        gboolean on = FALSE;
        if (g_variant_dict_lookup(opts, "capture", "b", &on)) capture_flag = on;
    }
    bool list_flag = false, append_flag = false;
    if (GVariantDict* opts = g_application_command_line_get_options_dict(cmd->gobj())) {
        gboolean on = FALSE;
        if (g_variant_dict_lookup(opts, "list", "b", &on)) list_flag = on;
        on = FALSE;
        if (g_variant_dict_lookup(opts, "append", "b", &on)) append_flag = on;
    }
    bool both_flag = false;
    if (GVariantDict* opts = g_application_command_line_get_options_dict(cmd->gobj())) {
        gboolean on = FALSE;
        if (g_variant_dict_lookup(opts, "both", "b", &on)) both_flag = on;
    }

    bool background_flag = false;
    if (GVariantDict* opts = g_application_command_line_get_options_dict(cmd->gobj())) {
        gboolean on = FALSE;
        if (g_variant_dict_lookup(opts, "background", "b", &on)) background_flag = on;
    }

    const Request r = parse(argv, capture_flag, list_flag, append_flag, both_flag);

    // ── jot --background (s074) ─────────────────────────────────────────────
    // The login autostart. A cold start builds the Shell and does NOT present
    // it: a window constructed and not shown is the resident state jot already
    // has (s012), so the due clock runs and captures land. Reaching a jot that
    // is already running it does nothing at all -- a second login entry, or a
    // stray run from a terminal, must not throw the window up or restart it.
    if (background_flag && !r.capture && !r.list && !r.append && !r.both) {
        if (cmd->is_remote()) {
            cmd->print("jot is already running.\n");
            return 0;
        }
        ensure_shell(/*present=*/false);
        if (auto lg = log::get(log::Area::App))
            lg->info("started in the background -- no window");
        return 0;
    }

    // ── jot NAME -al "line" item... (s061e) ────────────────────────────────
    // Arrives as --both NAME "line" items (core/Cli rewrote it). The line goes
    // in first, then the todos under it. Closed jot: two spool files, the line
    // first ("a" sorts before "b" in the same second).
    if (r.both) {
        if (r.words.size() < 3) {
            cmd->printerr("usage: jot NAME -al \"a line\" item [item...]\n"
                          "   or: jot NAME -a words... -l item [item...]\n"
                          "  e.g. jot Groceries -al \"for Saturday\" milk eggs\n");
            return 1;
        }
        const std::string name = r.words[0];
        std::string line = r.words[1];
        for (auto& c : line) if (c == '\n' || c == '\r') c = ' ';
        const std::vector<std::string> items(r.words.begin() + 2, r.words.end());
        if (!cmd->is_remote()) {
            std::string joined;
            std::size_t real = 0;
            for (const auto& it : items) {
                std::string one = it;
                for (auto& c : one) if (c == '\n' || c == '\r') c = ' ';
                if (!joined.empty()) joined += '\n';
                joined += one;
                std::vector<std::string> t;
                if (!core::pull_tags(it, t).empty()) ++real;
            }
            if (file_pending(line, {}, name, "a") && file_pending(joined, name, {}, "b")) {
                cmd->print("Filed a line and " + std::to_string(real) +
                           (real == 1 ? " item" : " items") + " for \"" + name +
                           "\". jot will add them next time it opens.\n");
                return 0;
            }
            cmd->printerr("jot: could not write to the pending folder; opening jot instead.\n");
        }
        ensure_shell(false);
        if (!m_shell) return 1;
        const std::string said = m_shell->capture_both(name, line, items);
        if (said.empty()) {
            cmd->printerr("jot: nothing to add.\n");
            return 1;
        }
        cmd->print(said + "\n");
        return 0;
    }

    // ── jot NAME -a words (s025d) ──────────────────────────────────────────
    // Same shape as --list below: never a window, answered in the terminal,
    // spooled when jot is closed.
    if (r.append && r.list) {
        cmd->printerr("jot: -l or -a, not both.\n");
        return 1;
    }
    if (r.append) {
        if (r.words.size() < 2) {
            cmd->printerr("usage: jot NAME -a words...\n"
                          "  e.g. jot Groceries -a check the pantry first\n");
            return 1;
        }
        const std::string name = r.words.front();
        std::string text;
        for (std::size_t i = 1; i < r.words.size(); ++i) {
            if (!text.empty()) text += ' ';
            text += r.words[i];
        }
        for (auto& c : text) if (c == '\n' || c == '\r') c = ' ';
        if (!cmd->is_remote()) {
            if (file_pending(text, {}, name)) {
                cmd->print("Filed a line for \"" + name + "\". jot will add it next time it opens.\n");
                return 0;
            }
            cmd->printerr("jot: could not write to the pending folder; opening jot instead.\n");
        }
        ensure_shell(false);
        if (!m_shell) return 1;
        const std::string said = m_shell->capture_append(name, text);
        if (said.empty()) {
            cmd->printerr("jot: nothing to add.\n");
            return 1;
        }
        cmd->print(said + "\n");
        return 0;
    }

    // ── jot --list NAME item... (s025c) ────────────────────────────────────
    // Never a window: it comes from a terminal or a script, and the terminal
    // is where it answers. Running -> filed now; not running -> spooled, and
    // the next launch files it through the same core::capture_list.
    if (r.list) {
        if (r.words.size() < 2) {
            cmd->printerr("usage: jot NAME -l item [item...]\n"
                          "  e.g. jot Groceries -l milk eggs \"sourdough bread\"\n");
            return 1;
        }
        const std::string name = r.words.front();
        const std::vector<std::string> items(r.words.begin() + 1, r.words.end());
        if (!cmd->is_remote()) {
            std::string joined;
            for (const auto& it : items) {
                if (!joined.empty()) joined += '\n';
                std::string one = it;
                for (auto& c : one) if (c == '\n' || c == '\r') c = ' ';
                joined += one;
            }
            std::size_t real = 0;   // s061d: a lone #tag tags the note; not an item
            for (const auto& it : items) {
                std::vector<std::string> t;
                if (!core::pull_tags(it, t).empty()) ++real;
            }
            if (file_pending(joined, name)) {
                cmd->print("Filed " + std::to_string(real) +
                           (real == 1 ? " item" : " items") + " for \"" + name +
                           "\". jot will add them next time it opens.\n");
                return 0;
            }
            cmd->printerr("jot: could not write to the pending folder; opening jot instead.\n");
        }
        ensure_shell(false);
        if (!m_shell) return 1;
        const std::string said = m_shell->capture_list(name, items);
        if (said.empty()) {
            cmd->printerr("jot: nothing to add.\n");
            return 1;
        }
        cmd->print(said + "\n");
        return 0;
    }
    // A capture with words in it is the one request that does NOT want to be
    // looked at: it comes from a script or a keybinding, and a window thrown in
    // front of whatever you were doing is the reason you would stop using it.
    const bool silent = r.capture && !r.text.empty();

    if (auto lg = log::get(log::Area::App))
        lg->debug("command-line: argc={} remote={} capture={} text='{}'", argc,
                  cmd->is_remote(), r.capture, r.text);

    // ── COLD CAPTURE: file it and go, with no window at all ────────────────
    // `is_remote()` false means this process IS the primary instance -- there
    // was no running jot to forward to. Starting the whole app to write one
    // line down is the behaviour this milestone exists to remove: the spool
    // takes it and the next launch drains it.
    if (silent && !cmd->is_remote()) {
        if (file_pending(r.text)) {
            // The terminal is the only surface this path has, so it says so.
            cmd->print("Filed. jot will pick it up next time it opens.\n");
            if (auto lg = log::get(log::Area::App))
                lg->info("cold capture -- spooled, no window");
            return 0;   // no window, no hold: the main loop has nothing left to do
        }
        // The spool is the only copy of what was typed, so a spool that failed
        // does not end in a shrug. Fall through and open jot, which turns an
        // unfilable capture into a live one rather than a lost one.
        cmd->printerr("jot: could not write to the pending folder; opening jot instead.\n");
        if (auto lg = log::get(log::Area::App))
            lg->error("cold capture -- spool write failed, falling back to opening jot");
    }

    // s062e: `./build/jot` (or the launcher) reaching an OLDER build that is
    // still running: say so in the terminal, and restart into the new one.
    // A capture is never a reason to restart -- the running jot files it.
    if (cmd->is_remote() && !r.capture && !r.list && !r.append && !r.both && stale()) {
        cmd->printerr("jot: an older build was running -- restarting it.\n");
        Glib::signal_idle().connect_once([this]() { restart_new_build(); });
        return 0;
    }

    // activate-or-repair, and present ONLY if something asked to be seen.
    ensure_shell(!silent);
    if (!m_shell) return 0;          // activation refused; nothing to capture into

    if (!r.capture) return 0;
    if (r.text.empty()) {
        m_shell->focus_capture_bar();
    } else {
        // s061: the warm path answers too -- the quick-settings tile reads this
        // line. A jot running with no folder open has no Inbox: the capture is
        // spooled, and the next folder opened takes it, rather than dropped.
        if (m_shell->capture(r.text)) {
            cmd->print("Filed to the Inbox.\n");
        } else if (file_pending(r.text)) {
            cmd->print("Filed. jot will pick it up when a jots folder is open.\n");
        } else {
            cmd->printerr("jot: no jots folder open and the pending folder could not be written.\n");
            return 1;
        }
        if (auto lg = log::get(log::Area::App)) lg->info("captured from the command line");
    }
    return 0;
}

// The XDG resolution is the UI layer's (core takes a plain path); the subpath
// is core's, so this and Shell::drain_pending cannot drift apart.
std::string App::pending_dir() const {
    return core::pending_dir(Glib::get_user_data_dir());
}

bool App::file_pending(const std::string& text, const std::string& list,
                       const std::string& append, const std::string& uniq_suffix) const {
    // The uniquifier only has to separate two captures taken in the same second.
    // A pid does that for separate invocations, which is what a cold capture
    // always is -- this process is about to exit.
    const auto now = std::chrono::duration_cast<std::chrono::seconds>(
                         std::chrono::system_clock::now().time_since_epoch())
                         .count();
    std::string wrote;
    if (!core::write_pending(pending_dir(), text, static_cast<std::int64_t>(now),
                             std::to_string(getpid()) + uniq_suffix, &wrote, list, append))
        return false;
    if (auto lg = log::get(log::Area::Io)) lg->info("spooled a capture into {}", wrote);
    return true;
}

// The SHORTCUT-REGISTRY paradigm's other consumer. Accelerators are an
// application-scope concern (they survive window construction order), so they
// bind here -- and they are driven from the pure core::shortcut_registry(), the
// same list ShortcutsDialog documents from. Register a shortcut once THERE and
// both the key and its advertised row follow; there is no second list to update
// and therefore nothing to drift. Doc-only rows (gestures) carry no action and
// are skipped -- they document without binding.
void App::on_startup() {
    Gtk::Application::on_startup();

    // Registered in startup so it exists before any activation can dispatch to
    // it -- including the one GNOME performs when a tray notification is
    // clicked on a jot that is not running.
    add_action_with_parameter(
        "goto-node", Glib::VARIANT_TYPE_STRING,
        sigc::mem_fun(*this, &App::on_goto_node));

    // s041: every BUTTON on a notification -- Mark done, In 1 hour, Tomorrow,
    // and whatever nudge comes next -- is this one action with a verb-and-key
    // parameter (core/NoticeAction). On the application for goto-node's
    // reason: the press can arrive with the window closed, or at no jot at all.
    add_action_with_parameter(
        "notice", Glib::VARIANT_TYPE_STRING,
        sigc::mem_fun(*this, &App::on_notice));

    // ── `app.quit`, and it is NOT decoration ───────────────────────────────
    // This is the action GNOME's Background Apps list activates over D-Bus when
    // you press Quit next to jot. GApplication exports org.freedesktop.
    // Application for free, and ActivateAction dispatches straight into this
    // group -- so an application that does not register a "quit" action is one
    // the Shell CANNOT ASK to stop, and it SIGKILLs the process instead. (KDE
    // hit this on the code they copied from gnome-shell's backgroundApps.js:
    // an app with no quit action gets killed, not asked.)
    //
    // For jot that would mean an unsaved scratch buffer dying with no prompt
    // and no chance to flush, in the one situation the milestone exists to
    // handle. So residency and this action arrive together, or residency is a
    // data-loss feature.
    //
    // Same reasoning as goto-node for it being on the APPLICATION: the request
    // arrives at a process whose window may have been closed an hour ago. It
    // does NOT activate() first, though -- unlike a notification click, "quit"
    // is not a reason to build a window. A quit with no Shell has nothing to
    // ask and nothing to save.
    add_action("quit", sigc::mem_fun(*this, &App::on_quit));
    for (const auto& s : core::shortcut_registry()) {
        if (s.action.empty() || s.accels.empty()) continue;
        std::vector<Glib::ustring> accels(s.accels.begin(), s.accels.end());
        set_accels_for_action(s.action, accels);
    }
}

// activate() FIRST, for the same reason on_command_line does it: the click may
// be arriving at a process that has no window yet, and there has to be a Shell
// before there is anything to reveal the node in. present() after, because
// unlike a scripted capture a notification click IS a request to be looked at.
void App::on_goto_node(const Glib::VariantBase& target) {
    auto v = Glib::VariantBase::cast_dynamic<Glib::Variant<Glib::ustring>>(target);
    const std::string id = v.get();
    if (id.empty()) return;

    activate();
    if (!m_shell) return;
    m_shell->present();
    m_shell->goto_note(id);
    if (auto lg = log::get(log::Area::App)) lg->info("notification opened node {}", id);
}

// A button is NOT a request to be looked at: "Mark done" from the tray should
// tick the todo and leave the screen alone. So the Shell is built if need be but
// never presented -- and a jot started only for this leaves again afterwards
// unless it is kept running in the background (after_cold_notice).
void App::on_notice(const Glib::VariantBase& target) {
    auto v = Glib::VariantBase::cast_dynamic<Glib::Variant<Glib::ustring>>(target);
    const std::string param = v.get();
    if (param.empty()) return;

    const bool cold = (m_shell == nullptr);
    ensure_shell(/*present=*/false);
    if (!m_shell) return;
    m_shell->notice_act(param);
    if (cold) m_shell->after_cold_notice();
}

// The Shell owns the decision, because it is the only object that knows whether
// there are unsaved notes -- and it may present the window to ask. With no
// Shell there is nothing to ask about and nothing to lose, so the process goes.
void App::on_quit() {
    if (auto lg = log::get(log::Area::App)) lg->info("quit requested");
    if (m_shell) m_shell->request_quit();
    else quit();
}

// activate() means "show me jot", and that is what the launcher, the desktop
// file and a notification click all mean by it. Everything it actually DOES is
// one layer down, where presenting is a parameter rather than an assumption.
void App::on_activate() {
    // s062e: the launcher reaching an older build -- restart into the new one.
    if (m_shell && stale()) {
        Glib::signal_idle().connect_once([this]() { restart_new_build(); });
        return;
    }
    ensure_shell(/*present=*/true);
}

// ─────────────────────────────────────────────────────────────────────────────
// ensure_shell -- there is a Shell, it is attached, and it may or may not be on
// screen.
//
// The `present` parameter is s013's two-line fix for a bug s012 created: a
// resident jot has no window, so EVERY arrival -- including `jot --capture
// "milk"` from a keybinding -- pulled the app onto the screen. What must always
// happen (construct, attach, build) and what must happen only on request
// (present) were the same statement, and separating them is the whole change.
// ─────────────────────────────────────────────────────────────────────────────
void App::ensure_shell(bool present) {
    // ── IDEMPOTENT, and it was not until s008 ───────────────────────────────
    // Until `jot --capture` existed, activate() happened exactly once per
    // process and this override could afford to assume it. It cannot now: a
    // forwarded command line calls activate() on the ALREADY RUNNING instance,
    // and without this guard that built a SECOND Shell -- a second window, a
    // second core::Project over the same jots folder, two writers to one
    // jot.json, and every widget name duplicated in the registry.
    //
    // The registry warned about the duplicates, which is the registry doing
    // exactly the job it exists to do: the second Shell was announced in the
    // log before anything was lost.
    if (m_shell) {
        // ── RE-ATTACH, because a hidden window loses its application ───────
        // s012 found this the hard way: while resident,
        // Gtk::Window::get_application() on the hidden Shell returns NULL. A
        // window with no application cannot resolve `app.*` through the action
        // muxer, which is why a re-presented jot came back with its menu items
        // and widgets insensitive -- they were not disabled, they had nothing
        // to dispatch to.
        //
        // add_window() is idempotent, so this costs nothing on the path where
        // the link survived and repairs the one where it did not.
        if (!m_shell->get_application()) {
            add_window(*m_shell);
            if (auto lg = log::get(log::Area::App))
                lg->warn("re-attached the hidden Shell to the application");
        }
        // The re-attach above happens EITHER WAY. A silent capture still has to
        // land in a Shell whose `app.*` actions resolve -- it just does not get
        // to put a window in front of anybody.
        if (present) m_shell->present();
        else if (auto lg = log::get(log::Area::App))
            // The line to grep for when checking that a scripted capture did
            // not steal the screen. The trace channel for a claim whose other
            // channel is permanently Scott's eyes.
            lg->info("silent arrival -- the window was left exactly as it was");
        return;
    }

    // ── THE DESKTOP'S LIGHT/DARK PREFERENCE, FIRST, BEFORE ANY WINDOW ───────
    // GTK4 does not follow it on its own and jot does not link libadwaita,
    // so the app has to ask (see Appearance.hpp). Ahead of `new Shell()` on
    // purpose: the difference between starting dark and starting light and
    // repainting.
    //
    // It also has to be ahead of the icon theme work below. The logo is a
    // SYMBOLIC icon, which GTK recolours to the theme foreground -- so it
    // inherits the answer to this question rather than carrying an opinion of
    // its own, and that is exactly why the bundle ships one symbolic SVG
    // instead of a light and a dark PNG.
    appearance::follow_system();

    // Register the compiled-in bundle and point the icon theme at its icon
    // prefix, so set_icon_name("jot-logo-symbolic") resolves out of the binary
    // and GTK recolours it to the theme foreground -- no icon on the user's disk.
    // NB: add_resource_path gets .../icons; GTK appends scalable/apps/ itself.
    g_resources_register(jot_resources_get_resource());
    if (auto display = Gdk::Display::get_default()) {
        auto icons = Gtk::IconTheme::get_for_display(display);
        icons->add_resource_path("/io/github/scott8420/Jot/icons");
    }

    m_shell = new Shell();       // lifetime owned by the application
    add_window(*m_shell);
    m_shell->build_ui();
    // present=false here is a notification BUTTON pressed on a jot that was
    // not running (s041): GNOME starts jot to deliver `app.notice`, and "Mark
    // done" is not a request to be looked at. A cold capture still spools
    // instead. A window constructed and deliberately not shown is the resident
    // state jot already supports, not a special case.
    if (present) m_shell->present();
    if (auto lg = log::get(log::Area::App)) lg->info("jot activated");
}

}  // namespace jot

namespace jot {

bool App::stale() const {
    if (m_exe.empty()) return false;
    char buf[4096];
    const ssize_t n = readlink("/proc/self/exe", buf, sizeof buf - 1);
    if (n > 0) {
        const std::string now(buf, static_cast<std::size_t>(n));
        if (now.size() > 10 && now.compare(now.size() - 10, 10, " (deleted)") == 0) return true;
    }
    struct stat st{};
    if (::stat(m_exe.c_str(), &st) != 0) return false;   // gone, nothing newer to run (yet)
    return static_cast<unsigned long long>(st.st_ino) != m_exe_ino ||
           static_cast<long long>(st.st_mtime) != m_exe_mtime;
}

bool App::restart_new_build() {
    if (m_exe.empty() || ::access(m_exe.c_str(), X_OK) != 0) {
        if (auto lg = log::get(log::Area::App))
            lg->warn("restart: no program at '{}' to run -- staying", m_exe);
        return false;
    }
    m_restart = m_exe;
    if (auto lg = log::get(log::Area::App))
        lg->info("restart: an older build was running -- quitting to run '{}'", m_exe);
    if (m_shell) m_shell->request_quit();
    else quit();
    return true;
}

}  // namespace jot
